export const enum Type {
  Fish,
  SeaCreature,
  Bug,
}
export const enum Frame {
  fish1,
  fish2,
  bug1,
  bug2,
  sea,
}

export const enum Critter {
  Bitterling,
  PaleChub,
  CrucianCarp,
  Dace,
  Carp,
  Koi,
  Goldfish,
  PopeyedGoldfish,
  RanchuGoldfish,
  Killifish,
  Crawfish,
  SoftShelledTurtle,
  SnappingTurtle,
  Tadpole,
  Frog,
  FreshwaterGoby,
  Loach,
  Catfish,
  GiantSnakehead,
  Bluegill,
  YellowPerch,
  BlackBass,
  Tilapia,
  Pike,
  PondSmelt,
  Sweetfish,
  CherrySalmon,
  Char,
  GoldenTrout,
  Stringfish,
  Salmon,
  KingSalmon,
  MittenCrab,
  Guppy,
  NibbleFish,
  Angelfish,
  Betta,
  NeonTetra,
  Rainbowfish,
  Piranha,
  Arowana,
  Dorado,
  Gar,
  Arapaima,
  SaddledBichir,
  Sturgeon,
  SeaButterfly,
  SeaHorse,
  ClownFish,
  Surgeonfish,
  ButterflyFish,
  Napoleonfish,
  ZebraTurkeyfish,
  Blowfish,
  PufferFish,
  Anchovy,
  HorseMackerel,
  BarredKnifejaw,
  SeaBass,
  RedSnapper,
  Dab,
  OliveFlounder,
  Squid,
  MorayEel,
  RibbonEel,
  Tuna,
  BlueMarlin,
  GiantTrevally,
  Mahimahi,
  OceanSunfish,
  Ray,
  SawShark,
  HammerheadShark,
  GreatWhiteShark,
  WhaleShark,
  Suckerfish,
  FootballFish,
  Oarfish,
  Barreleye,
  Coelacanth,
  CommonButterfly,
  YellowButterfly,
  TigerButterfly,
  PeacockButterfly,
  CommonBluebottle,
  PaperKiteButterfly,
  GreatPurpleEmperor,
  MonarchButterfly,
  EmperorButterfly,
  AgriasButterfly,
  RajahBrookesBirdwing,
  QueenAlexandrasBirdwing,
  Moth,
  AtlasMoth,
  MadagascanSunsetMoth,
  LongLocust,
  MigratoryLocust,
  RiceGrasshopper,
  Grasshopper,
  Cricket,
  BellCricket,
  Mantis,
  OrchidMantis,
  Honeybee,
  Wasp,
  BrownCicada,
  RobustCicada,
  GiantCicada,
  WalkerCicada,
  EveningCicada,
  CicadaShell,
  RedDragonfly,
  DarnerDragonfly,
  BandedDragonfly,
  Damselfly,
  Firefly,
  MoleCricket,
  Pondskater,
  DivingBeetle,
  GiantWaterBug,
  Stinkbug,
  ManFacedStinkBug,
  Ladybug,
  TigerBeetle,
  JewelBeetle,
  ViolinBeetle,
  CitrusLongHornedBeetle,
  RosaliaBatesiBeetle,
  BlueWeevilBeetle,
  DungBeetle,
  EarthBoringDungBeetle,
  ScarabBeetle,
  DroneBeetle,
  GoliathBeetle,
  SawStag,
  MiyamaStag,
  GiantStag,
  RainbowStag,
  CyclommatusStag,
  GoldenStag,
  GiraffeStag,
  HornedDynastid,
  HornedAtlas,
  HornedElephant,
  HornedHercules,
  WalkingStick,
  WalkingLeaf,
  Bagworm,
  Ant,
  HermitCrab,
  WharfRoach,
  Fly,
  Mosquito,
  Flea,
  Snail,
  PillBug,
  Centipede,
  Spider,
  Tarantula,
  Scorpion,
  Seaweed,
  SeaGrapes,
  SeaCucumber,
  SeaPig,
  SeaStar,
  SeaUrchin,
  SlatePencilUrchin,
  SeaAnemone,
  MoonJellyfish,
  SeaSlug,
  PearlOyster,
  Mussel,
  Oyster,
  Scallop,
  Whelk,
  TurbanShell,
  Abalone,
  GigasGiantClam,
  ChamberedNautilus,
  Octopus,
  UmbrellaOctopus,
  VampireSquid,
  FireflySquid,
  GazamiCrab,
  DungenessCrab,
  SnowCrab,
  RedKingCrab,
  AcornBarnacle,
  SpiderCrab,
  TigerPrawn,
  SweetShrimp,
  MantisShrimp,
  SpinyLobster,
  Lobster,
  GiantIsopod,
  HorseshoeCrab,
  SeaPineapple,
  SpottedGardenEel,
  Flatworm,
  VenusFlowerBasket,
}

export interface CritterInfo {
  name: string;
  frame: Frame;
  gridx: number;
  gridy: number;
  location: string;
  shadow?: number | string;
  northstart: number;
  northend: number;
  secondnorthstart?: number;
  secondnorthend?: number;
  southstart: number;
  southend: number;
  secondsouthstart?: number;
  secondsouthend?: number;
  hourstart: number;
  hourend: number;
  secondhourstart?: number;
  secondhourend?: number;
  caught?: boolean;
}

export const CritterInfo = [
  {
    name: "Bitterling",
    frame: Frame.fish1,
    gridx: 2,
    gridy: 3,
    location: "River",
    shadow: "1",
    northstart: 11,
    northend: 3,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 5,
    southend: 9,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Pale chub",
    frame: Frame.fish1,
    gridx: 2,
    gridy: 4,
    location: "River",
    shadow: "1",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 9,
    hourend: 16,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Crucian carp",
    frame: Frame.fish1,
    gridx: 2,
    gridy: 5,
    location: "River",
    shadow: "2",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Dace",
    frame: Frame.fish1,
    gridx: 2,
    gridy: 6,
    location: "River",
    shadow: "3",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 16,
    hourend: 9,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Carp",
    frame: Frame.fish1,
    gridx: 2,
    gridy: 7,
    location: "Pond",
    shadow: "4",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Koi",
    frame: Frame.fish1,
    gridx: 3,
    gridy: 3,
    location: "Pond",
    shadow: "4",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 16,
    hourend: 9,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Goldfish",
    frame: Frame.fish1,
    gridx: 3,
    gridy: 4,
    location: "Pond",
    shadow: "1",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Pop-eyed goldfish",
    frame: Frame.fish1,
    gridx: 3,
    gridy: 5,
    location: "Pond",
    shadow: "1",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 9,
    hourend: 16,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Ranchu goldfish",
    frame: Frame.fish1,
    gridx: 3,
    gridy: 6,
    location: "Pond",
    shadow: "2",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 9,
    hourend: 16,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Killifish",
    frame: Frame.fish1,
    gridx: 3,
    gridy: 7,
    location: "Pond",
    shadow: "1",
    northstart: 4,
    northend: 8,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 10,
    southend: 2,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Crawfish",
    frame: Frame.fish1,
    gridx: 4,
    gridy: 3,
    location: "Pond",
    shadow: "2",
    northstart: 4,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 10,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Soft-shelled turtle",
    frame: Frame.fish1,
    gridx: 4,
    gridy: 4,
    location: "River",
    shadow: "4",
    northstart: 8,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 2,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 16,
    hourend: 9,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Snapping Turtle",
    frame: Frame.fish1,
    gridx: 4,
    gridy: 5,
    location: "River",
    shadow: "4",
    northstart: 4,
    northend: 10,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 10,
    southend: 4,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 21,
    hourend: 4,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Tadpole",
    frame: Frame.fish1,
    gridx: 4,
    gridy: 6,
    location: "Pond",
    shadow: "1",
    northstart: 3,
    northend: 7,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 9,
    southend: 1,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Frog",
    frame: Frame.fish1,
    gridx: 4,
    gridy: 7,
    location: "Pond",
    shadow: "2",
    northstart: 5,
    northend: 8,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 11,
    southend: 2,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Freshwater goby",
    frame: Frame.fish1,
    gridx: 5,
    gridy: 3,
    location: "River",
    shadow: "2",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 16,
    hourend: 9,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Loach",
    frame: Frame.fish1,
    gridx: 5,
    gridy: 4,
    location: "River",
    shadow: "2",
    northstart: 3,
    northend: 5,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 9,
    southend: 11,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Catfish",
    frame: Frame.fish1,
    gridx: 5,
    gridy: 5,
    location: "Pond",
    shadow: "4",
    northstart: 5,
    northend: 10,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 11,
    southend: 4,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 16,
    hourend: 9,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Giant snakehead",
    frame: Frame.fish1,
    gridx: 5,
    gridy: 6,
    location: "Pond",
    shadow: "4",
    northstart: 6,
    northend: 8,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 12,
    southend: 2,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 9,
    hourend: 16,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Bluegill",
    frame: Frame.fish1,
    gridx: 5,
    gridy: 7,
    location: "River",
    shadow: "2",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 9,
    hourend: 16,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Yellow perch",
    frame: Frame.fish1,
    gridx: 6,
    gridy: 3,
    location: "River",
    shadow: "3",
    northstart: 10,
    northend: 3,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 4,
    southend: 9,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Black bass",
    frame: Frame.fish1,
    gridx: 6,
    gridy: 4,
    location: "River",
    shadow: "4",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Tilapia",
    frame: Frame.fish1,
    gridx: 6,
    gridy: 5,
    location: "River",
    shadow: "3",
    northstart: 6,
    northend: 10,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 12,
    southend: 4,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Pike",
    frame: Frame.fish1,
    gridx: 6,
    gridy: 6,
    location: "River",
    shadow: "5",
    northstart: 9,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 3,
    southend: 6,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Pond smelt",
    frame: Frame.fish1,
    gridx: 6,
    gridy: 7,
    location: "River",
    shadow: "2",
    northstart: 12,
    northend: 2,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 6,
    southend: 8,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Sweetfish",
    frame: Frame.fish1,
    gridx: 7,
    gridy: 3,
    location: "River",
    shadow: "3",
    northstart: 7,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Cherry salmon",
    frame: Frame.fish1,
    gridx: 7,
    gridy: 4,
    location: "River (Clifftop)",
    shadow: "3",
    northstart: 3,
    northend: 6,
    secondnorthstart: 9,
    secondnorthend: 11,
    southstart: 3,
    southend: 5,
    secondsouthstart: 9,
    secondsouthend: 12,
    hourstart: 16,
    hourend: 9,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Char",
    frame: Frame.fish1,
    gridx: 7,
    gridy: 5,
    location: "River (Clifftop) Pond",
    shadow: "3",
    northstart: 3,
    northend: 6,
    secondnorthstart: 9,
    secondnorthend: 11,
    southstart: 3,
    southend: 5,
    secondsouthstart: 9,
    secondsouthend: 12,
    hourstart: 16,
    hourend: 9,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Golden trout",
    frame: Frame.fish1,
    gridx: 7,
    gridy: 6,
    location: "River (Clifftop)",
    shadow: "3",
    northstart: 3,
    northend: 5,
    secondnorthstart: 9,
    secondnorthend: 11,
    southstart: 3,
    southend: 5,
    secondsouthstart: 9,
    secondsouthend: 11,
    hourstart: 16,
    hourend: 9,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Stringfish",
    frame: Frame.fish1,
    gridx: 7,
    gridy: 7,
    location: "River (Clifftop)",
    shadow: "5",
    northstart: 12,
    northend: 3,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 6,
    southend: 9,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 16,
    hourend: 9,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Salmon",
    frame: Frame.fish1,
    gridx: 8,
    gridy: 3,
    location: "River (Mouth)",
    shadow: "4",
    northstart: 9,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 3,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "King salmon",
    frame: Frame.fish1,
    gridx: 8,
    gridy: 4,
    location: "River (Mouth)",
    shadow: "5",
    northstart: 9,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 3,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Mitten crab",
    frame: Frame.fish1,
    gridx: 8,
    gridy: 5,
    location: "River",
    shadow: "2",
    northstart: 9,
    northend: 11,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 3,
    southend: 5,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 16,
    hourend: 9,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Guppy",
    frame: Frame.fish1,
    gridx: 8,
    gridy: 6,
    location: "River",
    shadow: "1",
    northstart: 4,
    northend: 11,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 10,
    southend: 5,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 9,
    hourend: 16,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Nibble fish",
    frame: Frame.fish1,
    gridx: 8,
    gridy: 7,
    location: "River",
    shadow: "1",
    northstart: 5,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 11,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 9,
    hourend: 16,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Angelfish",
    frame: Frame.fish1,
    gridx: 9,
    gridy: 3,
    location: "River",
    shadow: "2",
    northstart: 5,
    northend: 10,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 11,
    southend: 4,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 16,
    hourend: 9,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Betta",
    frame: Frame.fish1,
    gridx: 9,
    gridy: 4,
    location: "River",
    shadow: "2",
    northstart: 5,
    northend: 10,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 11,
    southend: 4,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 9,
    hourend: 16,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Neon tetra",
    frame: Frame.fish1,
    gridx: 9,
    gridy: 5,
    location: "River",
    shadow: "1",
    northstart: 4,
    northend: 11,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 10,
    southend: 5,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 9,
    hourend: 16,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Rainbowfish",
    frame: Frame.fish1,
    gridx: 9,
    gridy: 6,
    location: "River",
    shadow: "1",
    northstart: 5,
    northend: 10,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 11,
    southend: 4,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 9,
    hourend: 16,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Piranha",
    frame: Frame.fish1,
    gridx: 9,
    gridy: 7,
    location: "River",
    shadow: "2",
    northstart: 6,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 12,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 9,
    hourend: 16,
    secondhourstart: 21,
    secondhourend: 4,
    caught: false,
  },
  {
    name: "Arowana",
    frame: Frame.fish1,
    gridx: 10,
    gridy: 3,
    location: "River",
    shadow: "4",
    northstart: 6,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 12,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 16,
    hourend: 9,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Dorado",
    frame: Frame.fish1,
    gridx: 10,
    gridy: 4,
    location: "River",
    shadow: "5",
    northstart: 6,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 12,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 16,
    hourend: 9,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Gar",
    frame: Frame.fish1,
    gridx: 10,
    gridy: 5,
    location: "Pond",
    shadow: "5",
    northstart: 6,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 12,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 16,
    hourend: 9,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Arapaima",
    frame: Frame.fish1,
    gridx: 10,
    gridy: 6,
    location: "River",
    shadow: "6",
    northstart: 6,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 12,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 16,
    hourend: 9,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Saddled bichir",
    frame: Frame.fish1,
    gridx: 10,
    gridy: 7,
    location: "River",
    shadow: "4",
    northstart: 6,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 12,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 21,
    hourend: 4,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Sturgeon",
    frame: Frame.fish1,
    gridx: 11,
    gridy: 3,
    location: "River (Mouth)",
    shadow: "6",
    northstart: 9,
    northend: 3,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 3,
    southend: 9,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Sea butterfly",
    frame: Frame.fish1,
    gridx: 11,
    gridy: 4,
    location: "Sea",
    shadow: "1",
    northstart: 12,
    northend: 3,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 6,
    southend: 9,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Sea horse",
    frame: Frame.fish1,
    gridx: 11,
    gridy: 5,
    location: "Sea",
    shadow: "1",
    northstart: 4,
    northend: 11,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 10,
    southend: 5,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Clown fish",
    frame: Frame.fish1,
    gridx: 11,
    gridy: 6,
    location: "Sea",
    shadow: "1",
    northstart: 4,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 10,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Surgeonfish",
    frame: Frame.fish1,
    gridx: 11,
    gridy: 7,
    location: "Sea",
    shadow: "2",
    northstart: 4,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 10,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Butterfly fish",
    frame: Frame.fish2,
    gridx: 6,
    gridy: 3,
    location: "Sea",
    shadow: "2",
    northstart: 4,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 10,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Napoleonfish",
    frame: Frame.fish2,
    gridx: 6,
    gridy: 4,
    location: "Sea",
    shadow: "6",
    northstart: 7,
    northend: 8,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 2,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 4,
    hourend: 21,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Zebra turkeyfish",
    frame: Frame.fish2,
    gridx: 6,
    gridy: 5,
    location: "Sea",
    shadow: "3",
    northstart: 4,
    northend: 11,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 10,
    southend: 5,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Blowfish",
    frame: Frame.fish2,
    gridx: 6,
    gridy: 6,
    location: "Sea",
    shadow: "3",
    northstart: 11,
    northend: 2,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 5,
    southend: 8,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 21,
    hourend: 4,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Puffer fish",
    frame: Frame.fish2,
    gridx: 6,
    gridy: 7,
    location: "Sea",
    shadow: "3",
    northstart: 7,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Anchovy",
    frame: Frame.fish2,
    gridx: 7,
    gridy: 3,
    location: "Sea",
    shadow: "2",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 4,
    hourend: 21,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Horse mackerel",
    frame: Frame.fish2,
    gridx: 7,
    gridy: 4,
    location: "Sea",
    shadow: "2",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Barred knifejaw",
    frame: Frame.fish2,
    gridx: 7,
    gridy: 5,
    location: "Sea",
    shadow: "3",
    northstart: 3,
    northend: 11,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 9,
    southend: 5,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Sea bass",
    frame: Frame.fish2,
    gridx: 7,
    gridy: 6,
    location: "Sea",
    shadow: "5",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Red snapper",
    frame: Frame.fish2,
    gridx: 7,
    gridy: 7,
    location: "Sea",
    shadow: "4",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Dab",
    frame: Frame.fish2,
    gridx: 8,
    gridy: 3,
    location: "Sea",
    shadow: "3",
    northstart: 10,
    northend: 4,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 4,
    southend: 10,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Olive flounder",
    frame: Frame.fish2,
    gridx: 8,
    gridy: 4,
    location: "Sea",
    shadow: "5",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Squid",
    frame: Frame.fish2,
    gridx: 8,
    gridy: 5,
    location: "Sea",
    shadow: "3",
    northstart: 12,
    northend: 8,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 6,
    southend: 2,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Moray eel",
    frame: Frame.fish2,
    gridx: 8,
    gridy: 6,
    location: "Sea",
    shadow: "Narrow",
    northstart: 8,
    northend: 10,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 2,
    southend: 4,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Ribbon eel",
    frame: Frame.fish2,
    gridx: 8,
    gridy: 7,
    location: "Sea",
    shadow: "Narrow",
    northstart: 6,
    northend: 10,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 12,
    southend: 4,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Tuna",
    frame: Frame.fish2,
    gridx: 9,
    gridy: 3,
    location: "Pier",
    shadow: "6",
    northstart: 11,
    northend: 4,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 5,
    southend: 10,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Blue marlin",
    frame: Frame.fish2,
    gridx: 9,
    gridy: 4,
    location: "Pier",
    shadow: "6",
    northstart: 7,
    northend: 9,
    secondnorthstart: 11,
    secondnorthend: 4,
    southstart: 1,
    southend: 3,
    secondsouthstart: 5,
    secondsouthend: 11,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Giant trevally",
    frame: Frame.fish2,
    gridx: 9,
    gridy: 5,
    location: "Pier",
    shadow: "5",
    northstart: 5,
    northend: 10,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 11,
    southend: 4,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Mahi-mahi",
    frame: Frame.fish2,
    gridx: 9,
    gridy: 6,
    location: "Pier",
    shadow: "5",
    northstart: 5,
    northend: 10,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 11,
    southend: 4,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Ocean sunfish",
    frame: Frame.fish2,
    gridx: 9,
    gridy: 7,
    location: "Sea",
    shadow: "6 (Fin)",
    northstart: 7,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 4,
    hourend: 21,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Ray",
    frame: Frame.fish2,
    gridx: 10,
    gridy: 3,
    location: "Sea",
    shadow: "5",
    northstart: 8,
    northend: 11,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 2,
    southend: 5,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 4,
    hourend: 21,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Saw shark",
    frame: Frame.fish2,
    gridx: 10,
    gridy: 4,
    location: "Sea",
    shadow: "6 (Fin)",
    northstart: 6,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 12,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 16,
    hourend: 9,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Hammerhead shark",
    frame: Frame.fish2,
    gridx: 10,
    gridy: 5,
    location: "Sea",
    shadow: "6 (Fin)",
    northstart: 6,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 12,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 16,
    hourend: 9,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Great white shark",
    frame: Frame.fish2,
    gridx: 10,
    gridy: 6,
    location: "Sea",
    shadow: "6 (Fin)",
    northstart: 6,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 12,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 16,
    hourend: 9,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Whale shark",
    frame: Frame.fish2,
    gridx: 10,
    gridy: 7,
    location: "Sea",
    shadow: "6 (Fin)",
    northstart: 6,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 12,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Suckerfish",
    frame: Frame.fish2,
    gridx: 11,
    gridy: 3,
    location: "Sea",
    shadow: "6 (Fin)",
    northstart: 6,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 12,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Football fish",
    frame: Frame.fish2,
    gridx: 11,
    gridy: 4,
    location: "Sea",
    shadow: "4",
    northstart: 11,
    northend: 3,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 5,
    southend: 9,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 16,
    hourend: 9,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Oarfish",
    frame: Frame.fish2,
    gridx: 11,
    gridy: 5,
    location: "Sea",
    shadow: "6",
    northstart: 12,
    northend: 5,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 6,
    southend: 11,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Barreleye",
    frame: Frame.fish2,
    gridx: 11,
    gridy: 6,
    location: "Sea",
    shadow: "2",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 21,
    hourend: 4,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Coelacanth",
    frame: Frame.fish2,
    gridx: 11,
    gridy: 7,
    location: "Sea",
    shadow: "6",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Common Butterfly",
    frame: Frame.bug1,
    gridx: 2,
    gridy: 3,
    location: "Flying",
    shadow: "",
    northstart: 9,
    northend: 6,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 3,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 4,
    hourend: 19,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Yellow Butterfly",
    frame: Frame.bug1,
    gridx: 2,
    gridy: 4,
    location: "Flying",
    shadow: "",
    northstart: 3,
    northend: 6,
    secondnorthstart: 9,
    secondnorthend: 10,
    southstart: 3,
    southend: 4,
    secondsouthstart: 11,
    secondsouthend: 12,
    hourstart: 4,
    hourend: 19,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Tiger Butterfly",
    frame: Frame.bug1,
    gridx: 2,
    gridy: 5,
    location: "Flying",
    shadow: "",
    northstart: 3,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 9,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 4,
    hourend: 19,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Peacock Butterfly",
    frame: Frame.bug1,
    gridx: 2,
    gridy: 6,
    location: "Flying near blue, purple, and black flowers",
    shadow: "",
    northstart: 3,
    northend: 6,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 9,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 4,
    hourend: 19,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Common Bluebottle",
    frame: Frame.bug1,
    gridx: 2,
    gridy: 7,
    location: "Flying",
    shadow: "",
    northstart: 4,
    northend: 8,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 10,
    southend: 2,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 4,
    hourend: 19,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Paper Kite Butterfly",
    frame: Frame.bug1,
    gridx: 3,
    gridy: 3,
    location: "Flying near flowers",
    shadow: "",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 8,
    hourend: 19,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Great Purple Emperor",
    frame: Frame.bug1,
    gridx: 3,
    gridy: 4,
    location: "Flying near flowers",
    shadow: "",
    northstart: 5,
    northend: 8,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 11,
    southend: 2,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 4,
    hourend: 19,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Monarch Butterfly",
    frame: Frame.bug1,
    gridx: 3,
    gridy: 5,
    location: "Flying near flowers",
    shadow: "",
    northstart: 9,
    northend: 11,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 3,
    southend: 5,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 4,
    hourend: 17,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Emperor Butterfly",
    frame: Frame.bug1,
    gridx: 3,
    gridy: 6,
    location: "Flying near flowers",
    shadow: "",
    northstart: 6,
    northend: 9,
    secondnorthstart: 12,
    secondnorthend: 3,
    southstart: 12,
    southend: 3,
    secondsouthstart: 6,
    secondsouthend: 9,
    hourstart: 17,
    hourend: 8,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Agrias Butterfly",
    frame: Frame.bug1,
    gridx: 3,
    gridy: 7,
    location: "Flying near flowers",
    shadow: "",
    northstart: 4,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 11,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 8,
    hourend: 17,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Rajah Brooke's Birdwing",
    frame: Frame.bug1,
    gridx: 4,
    gridy: 3,
    location: "Flying near flowers",
    shadow: "",
    northstart: 4,
    northend: 9,
    secondnorthstart: 12,
    secondnorthend: 2,
    southstart: 11,
    southend: 3,
    secondsouthstart: 6,
    secondsouthend: 8,
    hourstart: 8,
    hourend: 17,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Queen Alexandra's Birdwing",
    frame: Frame.bug1,
    gridx: 4,
    gridy: 4,
    location: "Flying near flowers",
    shadow: "",
    northstart: 5,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 11,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 8,
    hourend: 16,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Moth",
    frame: Frame.bug1,
    gridx: 4,
    gridy: 5,
    location: "Flying near light sources",
    shadow: "",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 19,
    hourend: 4,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Atlas Moth",
    frame: Frame.bug1,
    gridx: 4,
    gridy: 6,
    location: "On trees (any kind)",
    shadow: "",
    northstart: 4,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 10,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 19,
    hourend: 4,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Madagascan Sunset Moth",
    frame: Frame.bug1,
    gridx: 4,
    gridy: 7,
    location: "Flying near flowers",
    shadow: "",
    northstart: 4,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 10,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 8,
    hourend: 16,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Long Locust",
    frame: Frame.bug1,
    gridx: 5,
    gridy: 3,
    location: "On the ground",
    shadow: "",
    northstart: 4,
    northend: 11,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 11,
    southend: 5,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 8,
    hourend: 19,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Migratory Locust",
    frame: Frame.bug1,
    gridx: 5,
    gridy: 4,
    location: "On the ground",
    shadow: "",
    northstart: 8,
    northend: 11,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 2,
    southend: 5,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 8,
    hourend: 19,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Rice Grasshopper",
    frame: Frame.bug1,
    gridx: 5,
    gridy: 5,
    location: "On the ground",
    shadow: "",
    northstart: 8,
    northend: 11,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 2,
    southend: 5,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 8,
    hourend: 19,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Grasshopper",
    frame: Frame.bug1,
    gridx: 5,
    gridy: 6,
    location: "On the ground",
    shadow: "",
    northstart: 7,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 8,
    hourend: 17,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Cricket",
    frame: Frame.bug1,
    gridx: 5,
    gridy: 7,
    location: "On the ground",
    shadow: "",
    northstart: 9,
    northend: 11,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 3,
    southend: 5,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 17,
    hourend: 8,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Bell Cricket",
    frame: Frame.bug1,
    gridx: 6,
    gridy: 3,
    location: "On the ground",
    shadow: "",
    northstart: 9,
    northend: 10,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 3,
    southend: 4,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 17,
    hourend: 8,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Mantis",
    frame: Frame.bug1,
    gridx: 6,
    gridy: 4,
    location: "On flowers",
    shadow: "",
    northstart: 3,
    northend: 11,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 9,
    southend: 5,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 8,
    hourend: 17,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Orchid Mantis",
    frame: Frame.bug1,
    gridx: 6,
    gridy: 5,
    location: "On white flowers",
    shadow: "",
    northstart: 3,
    northend: 11,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 9,
    southend: 5,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 8,
    hourend: 17,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Honeybee",
    frame: Frame.bug1,
    gridx: 6,
    gridy: 6,
    location: "Flying near flowers",
    shadow: "",
    northstart: 3,
    northend: 7,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 9,
    southend: 1,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 8,
    hourend: 17,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Wasp",
    frame: Frame.bug1,
    gridx: 6,
    gridy: 7,
    location: "Shaking trees",
    shadow: "",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Brown Cicada",
    frame: Frame.bug1,
    gridx: 7,
    gridy: 3,
    location: "On trees (hardwood and cedar)",
    shadow: "",
    northstart: 7,
    northend: 8,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 2,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 8,
    hourend: 17,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Robust Cicada",
    frame: Frame.bug1,
    gridx: 7,
    gridy: 4,
    location: "On trees (hardwood and cedar)",
    shadow: "",
    northstart: 7,
    northend: 8,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 2,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 8,
    hourend: 17,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Giant Cicada",
    frame: Frame.bug1,
    gridx: 7,
    gridy: 5,
    location: "On trees (hardwood and cedar)",
    shadow: "",
    northstart: 7,
    northend: 8,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 2,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 8,
    hourend: 17,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Walker Cicada",
    frame: Frame.bug1,
    gridx: 7,
    gridy: 6,
    location: "On trees (hardwood and cedar)",
    shadow: "",
    northstart: 8,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 2,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 8,
    hourend: 17,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Evening Cicada",
    frame: Frame.bug1,
    gridx: 7,
    gridy: 7,
    location: "On trees (hardwood and cedar)",
    shadow: "",
    northstart: 7,
    northend: 8,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 2,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 4,
    hourend: 8,
    secondhourstart: 16,
    secondhourend: 19,
    caught: false,
  },
  {
    name: "Cicada Shell",
    frame: Frame.bug1,
    gridx: 8,
    gridy: 3,
    location: "On trees (hardwood and cedar)",
    shadow: "",
    northstart: 7,
    northend: 8,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 2,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Red Dragonfly",
    frame: Frame.bug1,
    gridx: 8,
    gridy: 4,
    location: "Flying near water",
    shadow: "",
    northstart: 9,
    northend: 10,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 3,
    southend: 4,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 8,
    hourend: 19,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Darner Dragonfly",
    frame: Frame.bug1,
    gridx: 8,
    gridy: 5,
    location: "Flying near water",
    shadow: "",
    northstart: 4,
    northend: 10,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 10,
    southend: 4,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 8,
    hourend: 17,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Banded Dragonfly",
    frame: Frame.bug1,
    gridx: 8,
    gridy: 6,
    location: "Flying near water",
    shadow: "",
    northstart: 5,
    northend: 10,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 11,
    southend: 4,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 8,
    hourend: 17,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Damselfly",
    frame: Frame.bug1,
    gridx: 8,
    gridy: 7,
    location: "Flying near water",
    shadow: "",
    northstart: 11,
    northend: 2,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 5,
    southend: 8,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Firefly",
    frame: Frame.bug1,
    gridx: 9,
    gridy: 3,
    location: "Flying near water",
    shadow: "",
    northstart: 6,
    northend: 6,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 12,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 19,
    hourend: 4,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Mole Cricket",
    frame: Frame.bug1,
    gridx: 9,
    gridy: 4,
    location: "Underground",
    shadow: "",
    northstart: 11,
    northend: 5,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 5,
    southend: 11,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Pondskater",
    frame: Frame.bug1,
    gridx: 9,
    gridy: 5,
    location: "On rivers and ponds",
    shadow: "",
    northstart: 5,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 11,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 8,
    hourend: 19,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Diving Beetle",
    frame: Frame.bug1,
    gridx: 9,
    gridy: 6,
    location: "On rivers and ponds",
    shadow: "",
    northstart: 5,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 11,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 8,
    hourend: 19,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Giant Water Bug",
    frame: Frame.bug1,
    gridx: 9,
    gridy: 7,
    location: "On rivers and ponds",
    shadow: "",
    northstart: 4,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 10,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 19,
    hourend: 8,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Stinkbug",
    frame: Frame.bug1,
    gridx: 10,
    gridy: 3,
    location: "On flowers",
    shadow: "",
    northstart: 3,
    northend: 10,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 9,
    southend: 4,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Man-Faced Stink Bug",
    frame: Frame.bug1,
    gridx: 10,
    gridy: 4,
    location: "On flowers",
    shadow: "",
    northstart: 3,
    northend: 10,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 9,
    southend: 4,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 19,
    hourend: 8,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Ladybug",
    frame: Frame.bug1,
    gridx: 10,
    gridy: 5,
    location: "On flowers",
    shadow: "",
    northstart: 3,
    northend: 6,
    secondnorthstart: 10,
    secondnorthend: 10,
    southstart: 9,
    southend: 12,
    secondsouthstart: 4,
    secondsouthend: 4,
    hourstart: 8,
    hourend: 17,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Tiger Beetle",
    frame: Frame.bug1,
    gridx: 10,
    gridy: 6,
    location: "On the ground",
    shadow: "",
    northstart: 2,
    northend: 11,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 8,
    southend: 5,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Jewel Beetle",
    frame: Frame.bug1,
    gridx: 10,
    gridy: 7,
    location: "On tree stumps",
    shadow: "",
    northstart: 4,
    northend: 8,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 10,
    southend: 2,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Violin Beetle",
    frame: Frame.bug1,
    gridx: 11,
    gridy: 3,
    location: "On tree stumps",
    shadow: "",
    northstart: 5,
    northend: 6,
    secondnorthstart: 9,
    secondnorthend: 11,
    southstart: 11,
    southend: 12,
    secondsouthstart: 3,
    secondsouthend: 4,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Citrus Long-Horned Beetle",
    frame: Frame.bug1,
    gridx: 11,
    gridy: 4,
    location: "On tree stumps",
    shadow: "",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Rosalia Batesi Beetle",
    frame: Frame.bug1,
    gridx: 11,
    gridy: 5,
    location: "On tree stumps",
    shadow: "",
    northstart: 5,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 11,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Blue Weevil Beetle",
    frame: Frame.bug1,
    gridx: 11,
    gridy: 6,
    location: "On palm trees",
    shadow: "",
    northstart: 7,
    northend: 8,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 2,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Dung Beetle",
    frame: Frame.bug1,
    gridx: 11,
    gridy: 7,
    location: "Pushing snowballs",
    shadow: "",
    northstart: 12,
    northend: 2,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 6,
    southend: 8,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Earth-Boring Dung Beetle",
    frame: Frame.bug2,
    gridx: 6,
    gridy: 3,
    location: "On the ground",
    shadow: "",
    northstart: 7,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Scarab Beetle",
    frame: Frame.bug2,
    gridx: 6,
    gridy: 4,
    location: "On trees (any kind)",
    shadow: "",
    northstart: 7,
    northend: 8,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 2,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 23,
    hourend: 8,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Drone Beetle",
    frame: Frame.bug2,
    gridx: 6,
    gridy: 5,
    location: "On trees (any kind)",
    shadow: "",
    northstart: 6,
    northend: 8,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 12,
    southend: 2,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Goliath Beetle",
    frame: Frame.bug2,
    gridx: 6,
    gridy: 6,
    location: "On palm trees",
    shadow: "",
    northstart: 6,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 12,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 17,
    hourend: 8,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Saw Stag",
    frame: Frame.bug2,
    gridx: 6,
    gridy: 7,
    location: "On trees (any kind)",
    shadow: "",
    northstart: 7,
    northend: 8,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 2,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Miyama Stag",
    frame: Frame.bug2,
    gridx: 7,
    gridy: 3,
    location: "On trees (any kind)",
    shadow: "",
    northstart: 7,
    northend: 8,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 2,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Giant Stag",
    frame: Frame.bug2,
    gridx: 7,
    gridy: 4,
    location: "On trees (any kind)",
    shadow: "",
    northstart: 7,
    northend: 8,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 2,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 23,
    hourend: 8,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Rainbow Stag",
    frame: Frame.bug2,
    gridx: 7,
    gridy: 5,
    location: "On trees (any kind)",
    shadow: "",
    northstart: 6,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 12,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 19,
    hourend: 8,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Cyclommatus Stag",
    frame: Frame.bug2,
    gridx: 7,
    gridy: 6,
    location: "On palm trees",
    shadow: "",
    northstart: 7,
    northend: 8,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 2,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 17,
    hourend: 8,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Golden Stag",
    frame: Frame.bug2,
    gridx: 7,
    gridy: 7,
    location: "On palm trees",
    shadow: "",
    northstart: 7,
    northend: 8,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 2,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 17,
    hourend: 8,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Giraffe Stag",
    frame: Frame.bug2,
    gridx: 8,
    gridy: 3,
    location: "On palm trees",
    shadow: "",
    northstart: 7,
    northend: 8,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 2,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 17,
    hourend: 8,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Horned Dynastid",
    frame: Frame.bug2,
    gridx: 8,
    gridy: 4,
    location: "On trees (any kind)",
    shadow: "",
    northstart: 7,
    northend: 8,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 2,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 17,
    hourend: 8,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Horned Atlas",
    frame: Frame.bug2,
    gridx: 8,
    gridy: 5,
    location: "On palm trees",
    shadow: "",
    northstart: 7,
    northend: 8,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 2,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 17,
    hourend: 8,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Horned Elephant",
    frame: Frame.bug2,
    gridx: 8,
    gridy: 6,
    location: "On palm trees",
    shadow: "",
    northstart: 7,
    northend: 8,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 2,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 17,
    hourend: 8,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Horned Hercules",
    frame: Frame.bug2,
    gridx: 8,
    gridy: 7,
    location: "On palm trees",
    shadow: "",
    northstart: 7,
    northend: 8,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 2,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 17,
    hourend: 8,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Walking Stick",
    frame: Frame.bug2,
    gridx: 9,
    gridy: 3,
    location: "On trees (any kind)",
    shadow: "",
    northstart: 7,
    northend: 11,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 5,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 4,
    hourend: 8,
    secondhourstart: 17,
    secondhourend: 19,
    caught: false,
  },
  {
    name: "Walking Leaf",
    frame: Frame.bug2,
    gridx: 9,
    gridy: 4,
    location: "Disguised under trees",
    shadow: "",
    northstart: 7,
    northend: 8,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Bagworm",
    frame: Frame.bug2,
    gridx: 9,
    gridy: 5,
    location: "Shaking trees (hardwood and cedar)",
    shadow: "",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Ant",
    frame: Frame.bug2,
    gridx: 9,
    gridy: 6,
    location: "On rotten Turnips/Candy/Lollipops",
    shadow: "",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Hermit Crab",
    frame: Frame.bug2,
    gridx: 9,
    gridy: 7,
    location: "Disguised on shoreline",
    shadow: "",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 19,
    hourend: 8,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Wharf Roach",
    frame: Frame.bug2,
    gridx: 10,
    gridy: 3,
    location: "On beach rocks",
    shadow: "",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Fly",
    frame: Frame.bug2,
    gridx: 10,
    gridy: 4,
    location: "Flying near trash or rotten turnips",
    shadow: "",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Mosquito",
    frame: Frame.bug2,
    gridx: 10,
    gridy: 5,
    location: "Flying",
    shadow: "",
    northstart: 6,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 12,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 17,
    hourend: 4,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Flea",
    frame: Frame.bug2,
    gridx: 10,
    gridy: 6,
    location: "On villagers",
    shadow: "",
    northstart: 4,
    northend: 11,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 10,
    southend: 5,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Snail",
    frame: Frame.bug2,
    gridx: 10,
    gridy: 7,
    location: "On rocks and bushes",
    shadow: "",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Pill Bug",
    frame: Frame.bug2,
    gridx: 11,
    gridy: 3,
    location: "From hitting rocks",
    shadow: "",
    northstart: 9,
    northend: 6,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 3,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 23,
    hourend: 16,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Centipede",
    frame: Frame.bug2,
    gridx: 11,
    gridy: 4,
    location: "From hitting rocks",
    shadow: "",
    northstart: 9,
    northend: 6,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 3,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 16,
    hourend: 23,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Spider",
    frame: Frame.bug2,
    gridx: 11,
    gridy: 5,
    location: "Shaking trees",
    shadow: "",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 19,
    hourend: 8,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Tarantula",
    frame: Frame.bug2,
    gridx: 11,
    gridy: 6,
    location: "On the ground",
    shadow: "",
    northstart: 11,
    northend: 4,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 5,
    southend: 10,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 19,
    hourend: 4,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Scorpion",
    frame: Frame.bug2,
    gridx: 11,
    gridy: 7,
    location: "On the ground",
    shadow: "",
    northstart: 5,
    northend: 10,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 11,
    southend: 4,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 19,
    hourend: 4,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Seaweed",
    frame: Frame.sea,
    gridx: 3,
    gridy: 3,
    location: "Diving",
    shadow: "Stationary",
    northstart: 10,
    northend: 7,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 4,
    southend: 1,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Sea Grapes",
    frame: Frame.sea,
    gridx: 3,
    gridy: 4,
    location: "Diving",
    shadow: "Stationary",
    northstart: 6,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 12,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Sea Cucumber",
    frame: Frame.sea,
    gridx: 3,
    gridy: 5,
    location: "Diving",
    shadow: "Very slow",
    northstart: 11,
    northend: 4,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 5,
    southend: 10,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Sea Pig",
    frame: Frame.sea,
    gridx: 3,
    gridy: 6,
    location: "Diving",
    shadow: "Very fast",
    northstart: 11,
    northend: 2,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 5,
    southend: 8,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 16,
    hourend: 9,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Sea Star",
    frame: Frame.sea,
    gridx: 3,
    gridy: 7,
    location: "Diving",
    shadow: "Very slow",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Sea Urchin",
    frame: Frame.sea,
    gridx: 4,
    gridy: 3,
    location: "Diving",
    shadow: "Slow",
    northstart: 5,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 11,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Slate Pencil Urchin",
    frame: Frame.sea,
    gridx: 4,
    gridy: 4,
    location: "Diving",
    shadow: "Medium",
    northstart: 5,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 11,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 16,
    hourend: 9,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Sea Anemone",
    frame: Frame.sea,
    gridx: 4,
    gridy: 5,
    location: "Diving",
    shadow: "Stationary",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Moon Jellyfish",
    frame: Frame.sea,
    gridx: 4,
    gridy: 6,
    location: "Diving",
    shadow: "Very slow",
    northstart: 7,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Sea Slug",
    frame: Frame.sea,
    gridx: 4,
    gridy: 7,
    location: "Diving",
    shadow: "Very slow",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Pearl Oyster",
    frame: Frame.sea,
    gridx: 5,
    gridy: 3,
    location: "Diving",
    shadow: "Medium",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Mussel",
    frame: Frame.sea,
    gridx: 5,
    gridy: 4,
    location: "Diving",
    shadow: "Slow",
    northstart: 6,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 12,
    southend: 6,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Oyster",
    frame: Frame.sea,
    gridx: 5,
    gridy: 5,
    location: "Diving",
    shadow: "Slow",
    northstart: 9,
    northend: 2,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 3,
    southend: 8,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Scallop",
    frame: Frame.sea,
    gridx: 5,
    gridy: 6,
    location: "Diving",
    shadow: "Slow",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Whelk",
    frame: Frame.sea,
    gridx: 5,
    gridy: 7,
    location: "Diving",
    shadow: "Slow",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Turban Shell",
    frame: Frame.sea,
    gridx: 6,
    gridy: 3,
    location: "Diving",
    shadow: "Slow",
    northstart: 3,
    northend: 5,
    secondnorthstart: 9,
    secondnorthend: 12,
    southstart: 3,
    southend: 6,
    secondsouthstart: 9,
    secondsouthend: 11,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Abalone",
    frame: Frame.sea,
    gridx: 6,
    gridy: 4,
    location: "Diving",
    shadow: "Medium",
    northstart: 6,
    northend: 1,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 12,
    southend: 7,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 16,
    hourend: 9,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Gigas Giant Clam",
    frame: Frame.sea,
    gridx: 6,
    gridy: 5,
    location: "Diving",
    shadow: "Very fast",
    northstart: 5,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 11,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Chambered Nautilus",
    frame: Frame.sea,
    gridx: 6,
    gridy: 6,
    location: "Diving",
    shadow: "Medium",
    northstart: 3,
    northend: 6,
    secondnorthstart: 9,
    secondnorthend: 11,
    southstart: 9,
    southend: 12,
    secondsouthstart: 3,
    secondsouthend: 5,
    hourstart: 16,
    hourend: 9,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Octopus",
    frame: Frame.sea,
    gridx: 6,
    gridy: 7,
    location: "Diving",
    shadow: "Slow",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Umbrella Octopus",
    frame: Frame.sea,
    gridx: 7,
    gridy: 3,
    location: "Diving",
    shadow: "Fast",
    northstart: 3,
    northend: 5,
    secondnorthstart: 9,
    secondnorthend: 11,
    southstart: 3,
    southend: 5,
    secondsouthstart: 9,
    secondsouthend: 11,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Vampire Squid",
    frame: Frame.sea,
    gridx: 7,
    gridy: 4,
    location: "Diving",
    shadow: "Very fast",
    northstart: 5,
    northend: 8,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 11,
    southend: 2,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 16,
    hourend: 9,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Firefly Squid",
    frame: Frame.sea,
    gridx: 7,
    gridy: 5,
    location: "Diving",
    shadow: "Slow",
    northstart: 3,
    northend: 6,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 9,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 21,
    hourend: 4,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Gazami Crab",
    frame: Frame.sea,
    gridx: 7,
    gridy: 6,
    location: "Diving",
    shadow: "Medium",
    northstart: 6,
    northend: 11,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 12,
    southend: 5,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Dungeness Crab",
    frame: Frame.sea,
    gridx: 7,
    gridy: 7,
    location: "Diving",
    shadow: "Medium",
    northstart: 11,
    northend: 5,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 5,
    southend: 11,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Snow Crab",
    frame: Frame.sea,
    gridx: 8,
    gridy: 3,
    location: "Diving",
    shadow: "Fast",
    northstart: 11,
    northend: 4,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 5,
    southend: 10,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Red King Crab",
    frame: Frame.sea,
    gridx: 8,
    gridy: 4,
    location: "Diving",
    shadow: "Very fast",
    northstart: 11,
    northend: 3,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 5,
    southend: 9,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Acorn Barnacle",
    frame: Frame.sea,
    gridx: 8,
    gridy: 5,
    location: "Diving",
    shadow: "Stationary",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Spider Crab",
    frame: Frame.sea,
    gridx: 8,
    gridy: 6,
    location: "Diving",
    shadow: "Very fast",
    northstart: 3,
    northend: 4,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 9,
    southend: 10,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Tiger Prawn",
    frame: Frame.sea,
    gridx: 8,
    gridy: 7,
    location: "Diving",
    shadow: "Medium",
    northstart: 6,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 12,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 16,
    hourend: 9,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Sweet Shrimp",
    frame: Frame.sea,
    gridx: 9,
    gridy: 3,
    location: "Diving",
    shadow: "Slow",
    northstart: 9,
    northend: 2,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 3,
    southend: 8,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 16,
    hourend: 9,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Mantis Shrimp",
    frame: Frame.sea,
    gridx: 9,
    gridy: 4,
    location: "Diving",
    shadow: "Medium",
    northstart: 1,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 12,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 16,
    hourend: 9,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Spiny Lobster",
    frame: Frame.sea,
    gridx: 9,
    gridy: 5,
    location: "Diving",
    shadow: "Fast",
    northstart: 10,
    northend: 12,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 4,
    southend: 6,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 21,
    hourend: 4,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Lobster",
    frame: Frame.sea,
    gridx: 9,
    gridy: 6,
    location: "Diving",
    shadow: "Fast",
    northstart: 4,
    northend: 6,
    secondnorthstart: 12,
    secondnorthend: 1,
    southstart: 10,
    southend: 12,
    secondsouthstart: 6,
    secondsouthend: 7,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Giant Isopod",
    frame: Frame.sea,
    gridx: 9,
    gridy: 7,
    location: "Diving",
    shadow: "Very fast",
    northstart: 7,
    northend: 10,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 4,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 9,
    hourend: 16,
    secondhourstart: 21,
    secondhourend: 4,
    caught: false,
  },
  {
    name: "Horseshoe Crab",
    frame: Frame.sea,
    gridx: 10,
    gridy: 3,
    location: "Diving",
    shadow: "Medium",
    northstart: 7,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 1,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 21,
    hourend: 4,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Sea Pineapple",
    frame: Frame.sea,
    gridx: 10,
    gridy: 4,
    location: "Diving",
    shadow: "Slow",
    northstart: 4,
    northend: 8,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 12,
    southend: 7,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Spotted Garden Eel",
    frame: Frame.sea,
    gridx: 10,
    gridy: 5,
    location: "Diving",
    shadow: "Slow",
    northstart: 5,
    northend: 10,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 11,
    southend: 4,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 4,
    hourend: 21,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Flatworm",
    frame: Frame.sea,
    gridx: 10,
    gridy: 6,
    location: "Diving",
    shadow: "Very slow",
    northstart: 8,
    northend: 9,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 2,
    southend: 3,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 16,
    hourend: 9,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
  {
    name: "Venus' Flower Basket",
    frame: Frame.sea,
    gridx: 10,
    gridy: 7,
    location: "Diving",
    shadow: "Fast",
    northstart: 10,
    northend: 2,
    secondnorthstart: null,
    secondnorthend: null,
    southstart: 4,
    southend: 8,
    secondsouthstart: null,
    secondsouthend: null,
    hourstart: 0,
    hourend: 24,
    secondhourstart: null,
    secondhourend: null,
    caught: false,
  },
];
